apiVersion: apps/v1
kind: Deployment
metadata:
  name: distance-monitor
  namespace: vehicle-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distance-monitor
  template:
    metadata:
      labels:
        app: distance-monitor
    spec:
      containers:
      - name: distance-monitor
        image: distance-monitor-service:20250515-132443
        ports:
        - containerPort: 5000
