apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-tracker
  namespace: vehicle-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-tracker
  template:
    metadata:
      labels:
        app: location-tracker
    spec:
      containers:
      - name: location-tracker
        image: location-tracker-service:20250515-121310
        ports:
        - containerPort: 5000
