apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datamock
  template:
    metadata:
      labels:
        app: datamock
    spec:
      containers:
      - name: datamock
        image: datamock:latest
        ports:
        - containerPort: 5000
