apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamock
  namespace: vehicle-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datamock
  template:
    metadata:
      labels:
        app: datamock
    spec:
      containers:
      - name: datamock
        image: datamock-service:20250515-121310
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
