apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-sender
  namespace: vehicle-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-sender
  template:
    metadata:
      labels:
        app: location-sender
    spec:
      containers:
      - name: location-sender
        image: location-sender-service:20250515-122510
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: username
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: password
