apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-sender
  namespace: vehicle-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-sender
  template:
    metadata:
      labels:
        app: location-sender
    spec:
      initContainers:
            - name: wait-for-rabbitmq
              image: busybox
              command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
      - name: location-sender
        image: location-sender-service:20250515-143434
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: username
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-credentials
                key: password
