apiVersion: v1
kind: Service
metadata:
  name: location-sender
  namespace: vehicle-platform
spec:
  selector:
    app: location-sender
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP # internal access only
